AWSTemplateFormatVersion: 2010-09-09

Description: This Template Create an RDS in Data subnet.
Parameters: 

  
 VPCId:
  Description: Put a VPC Id here
  Type: String
  Default: vpc-07769cfeddd4729ac
    
 PublicSubnetId:
  Description: Put a subnet Id here
  Type: String
  Default: subnet-09f88259c2cab7f90
  
 PublicSubnetId01:
  Description: Put a subnet Id here
  Type: String
  Default: subnet-040817b226556f3d0

Resources:
 RDSSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: RDS Security Group
    VpcId: !Ref VPCId

 RDSSubnetGroup:
  Type: AWS::RDS::DBSubnetGroup
  Properties:
    DBSubnetGroupName: RDSSubnetGroup
    DBSubnetGroupDescription: RDS Subnet Group
    SubnetIds:
      - !Ref PublicSubnetId
      - !Ref PublicSubnetId01

 RDSInstance:
  Type: AWS::RDS::DBInstance
  Properties:
    Engine: mysql
    EngineVersion: 5.7
    DBInstanceIdentifier: MyDBInstance
    MasterUsername: admin
    MasterUserPassword: admin123
    AllocatedStorage: 20
    DBInstanceClass: db.t2.micro
    VPCSecurityGroups:
      - !Ref RDSSecurityGroup
    DBSubnetGroupName: !Ref RDSSubnetGroup

Outputs:
 RDSInstanceEndpoint:
  Description: Endpoint URL of the RDS instance
  Value: !GetAtt RDSInstance.Endpoint.Address
